### ISSUE TITLE
Failed to run amcheck with Postgresql 15.2 on Debian

### ISSUE THREAD

**Issue by rafaelp** [vitabaks/pgbackrest_auto#12]
When running the command to create extension amcheck the script fail and return
`ERROR: CREATE EXTENSION amcheck failed`

The command is in this line: https://github.com/vitabaks/pgbackrest_auto/blob/master/pgbackrest_auto#L594

When I run by hand:

    $ psql -v "ON_ERROR_STOP" -p "${PGPORT}" -h 127.0.0.1 -U postgres -d "postgres" -tAXc "CREATE EXTENSION if not exists amcheck"

 I get the following PostgreSQL error:

`ERROR:  could not access file "$libdir/pgaudit": No such file or director`

It seem that to be able to install amcheck pgaudit is required, so I've installed pgaudit via `sudo apt-get install postgresql-15-pgaudit`.

After that, running the command to create extension again, I get:

`ERROR:  pgaudit must be loaded via shared_preload_libraries`

I see that postgresql is started at https://github.com/vitabaks/pgbackrest_auto/blob/master/pgbackrest_auto#L465

The solution would be to set shared_preload_libraries config for this instance that is loaded.

**Comment by vitabaks** [comment]
Hi @rafaelp 

Unfortunately, I cannot determine all the dependencies in your database at the `pgbackrest_auto` level. 

Therefore, you need to take care of it yourself.  \
You can try setting the `shared_preload_libraries` parameter via the `alter system` command on the source database so that the parameter gets into the `postgresql.auto.conf` configuration file, which will then be used when starting a temporary PostgreSQL instance during the restore. 

Or define the necessary parameter in the `postgresql_conf()` function - https://github.com/vitabaks/pgbackrest_auto/blob/master/pgbackrest_auto#LL623-L623C28

**Comment by rafaelp** [comment]
hi @vitabaks thanks for your response!

I understood this was a dependency of amcheck not my database.

**Comment by rafaelp** [comment]
Anyway I could fix by adding the following line in `postgresql_conf()`:

```
# enable pgaudit to run  amcheck
echo "shared_preload_libraries = 'pgaudit'" >> "${PG_CONF_DIR}"/postgresql.conf
```

Thanks again for the help.
