### ISSUE TITLE
/usr/bin/pgbackrest_auto: line 430: pg_isready: command not found

### ISSUE THREAD

**Issue by prensgold** [vitabaks/pgbackrest_auto#6]
Hi Vitaliy ,

i'm trying to setting your  script .
pgisready steps are giving same error as cycle.
Is pg_isready misspelled inside the function?

```
2023-01-18 09:32:47 INFO: Restore from backup done
2023-01-18 09:32:47 INFO: [STEP 4]: PostgreSQL Starting for recovery
2023-01-18 09:32:47 INFO: PostgreSQL start
/usr/bin/pgbackrest_auto: line 430: pg_isready: command not found
2023-01-18 09:32:49 INFO: attempt: 1/3600
/usr/bin/pgbackrest_auto: line 430: pg_isready: command not found
2023-01-18 09:32:49 WARN: PostgreSQL instance data no response
2023-01-18 09:32:50 INFO: attempt: 2/3600
/usr/bin/pgbackrest_auto: line 430: pg_isready: command not found
2023-01-18 09:32:50 WARN: PostgreSQL instance data no response
2023-01-18 09:32:51 INFO: attempt: 3/3600
/usr/bin/pgbackrest_auto: line 430: pg_isready: command not found
2023-01-18 09:32:51 WARN: PostgreSQL instance data no response
```

When pg_isready is changed to pgisready, it gives segment fault error as below.
```
Jan 18 09:39:12 dbtest01 pgbackrest_auto[1456198]: See detailed log in the file /var/log/pgbackrest/stanza-restore.log
Jan 18 09:39:21 dbtest01 pgbackrest_auto[1456461]: Restore from backup done
Jan 18 09:39:21 dbtest01 pgbackrest_auto[1456485]: [STEP 4]: PostgreSQL Starting for recovery
Jan 18 09:39:21 dbtest01 pgbackrest_auto[1456488]: PostgreSQL start
Jan 18 09:39:33 dbtest01 kernel: pgbackrest_auto[1455941]: segfault at 7ffd7f0c6fc8 ip 00007f8c0b727f39 sp 00007ffd7f0c6fa0 error 6 in libc-2.28.so[7f8c0b68d000+1bc000]
Jan 18 09:39:33 dbtest01 systemd-coredump[1457118]: Resource limits disable core dumping for process 1455941 (pgbackrest_auto).
Jan 18 09:39:33 dbtest01 systemd-coredump[1457118]: Process 1455941 (pgbackrest_auto) of user 53002 dumped core.

```
Thanks

**Comment by prensgold** [comment]
Is there an operating system dependency?
I'm trying to run it on Red Hat 8.6.

**Comment by vitabaks** [comment]
Hi @prensgold 

most likely, you do not have a `PATH` to the bin directory where the `pg_isready` utility is located.

Example:

`PATH=$PATH:/usr/pgsql-14/bin`

you can check the PATH using the `env` command.

**Comment by vitabaks** [comment]
at the moment, the script is optimized for debian/ubuntu because the paths `/usr/lib/postgresql/"${PGVER}"/bin/` are specified Instead of `/usr/pgsql-"${PGVER}"/bin` for RHEL based distros. \
And also the `pg_ctlcluster` command is used (which as far as I know is not in RHEL-based distributions) Instead of `pg_ctl` command.

I will fix it soon, for better compatibility with RHEL.

**Comment by prensgold** [comment]
Thanks @vitabaks , When I set the PATH at the beginning of the script, the problem was fixed.
I used sudo systemctl status postgresql-"${PGVER}".service instead of pg_ctlcluster.

**Comment by vitabaks** [comment]
@prensgold please test the version from this PR https://github.com/vitabaks/pgbackrest_auto/pull/8

```
wget https://raw.githubusercontent.com/vitabaks/pgbackrest_auto/redhat-compatibility/pgbackrest_auto
sudo mv pgbackrest_auto /usr/bin/
sudo chown postgres:postgres /usr/bin/pgbackrest_auto
sudo chmod 750 /usr/bin/pgbackrest_auto
```

**Comment by prensgold** [comment]
Hi @vitabaks ,

Postgresql is installed somewhere other than the default installation locations.
in this case it caused me to get the following errors.
I had to modify the script for my installation locations.
Is it possible to get the paths dynamically?like postgresql.conf location

[postgres@dbtest01 bin]$  /usr/bin/pgbackrest_auto --config=/etc/pgbackrest.conf --from=stanza --to=/u01/pgdata/14/data --checkdb
2023-01-30 10:43:49 ERROR: port not found or missing /etc/postgresql/14/data/postgresql.conf file
[postgres@dbtest01 bin]$ 


[postgres@dbtest01 bin]$  /usr/bin/pgbackrest_auto --config=/etc/pgbackrest.conf --from=stanza --to=/u01/pgdata/14/data --checkdb
2023-01-30 10:26:26 WARN: pg_checksums command not be found. Please install the postgresql-14-pg-checksums package
[postgres@dbtest01 bin]$ 

[postgres@dbtest01 bin]$ which pg_checksums
/usr/pgsql-14/bin/pg_checksums
[postgres@dbtest01 bin]$

**Comment by vitabaks** [comment]
> Postgresql is installed somewhere other than the default installation locations.
in this case it caused me to get the following errors.

it is assumed that postgresql is installed from packages in the default path. Otherwise, you will need to override `PG_BIN_DIR` variable.

**upd**: I described it in the README https://github.com/vitabaks/pgbackrest_auto/pull/8/commits/721499c7b7e61fb487c88a9ed27aa1f86fc619ca.

> ERROR: port not found or missing /etc/postgresql/14/data/postgresql.conf file

This means that you are using version 1.4.0. In the new [version](https://github.com/vitabaks/pgbackrest_auto/blob/redhat-compatibility/pgbackrest_auto#L11) 5432 is set by default (for tests), and I plan to make a dynamic port allocation.

please download version 1.5.0
`wget https://raw.githubusercontent.com/vitabaks/pgbackrest_auto/redhat-compatibility/pgbackrest_auto`

> WARN: pg_checksums command not be found. Please install the postgresql-14-pg-checksums package

download the [latest](https://github.com/vitabaks/pgbackrest_auto/blob/redhat-compatibility/pgbackrest_auto) version of the script. It looks like you have the PG_BIN_DIR specified incorrectly

https://github.com/vitabaks/pgbackrest_auto/blob/redhat-compatibility/pgbackrest_auto#L286

> /pgbackrest_auto --config=/etc/pgbackrest.conf

There is no config option right now, but I'm thinking of adding it

At the moment we are just redefining the [config](https://github.com/vitabaks/pgbackrest_auto/blob/redhat-compatibility/pgbackrest_auto#L327) to /tmp/pgbackrest_auto.conf 

**upd**: added option `--config` https://github.com/vitabaks/pgbackrest_auto/pull/8/commits/01e8ce56570a035a8f1467940d0b4013a72aca83

**Comment by prensgold** [comment]
I was able to run it without any problems after your update.

I have seen such warnings in the logs except for your script.
Do you think this is normal behavior?

2023-01-30 18:07:29 INFO:   starting pg_dump -p 5432 -h 127.0.0.1 -d ProIOT >> /dev/null
2023-01-30 18:07:30 INFO: Data validation in the database ProIOT - Successful
2023-01-30 18:07:30 INFO: Start data validation for database test
2023-01-30 18:07:30 INFO:   starting pg_dump -p 5432 -h 127.0.0.1 -d test >> /dev/null
_**pg_dump: warning: could not resolve dependency loop among these items:**_
pg_dump:   INDEX events_daily_p2022_01_01_pkey  (ID 6378 OID 49839)
pg_dump:   CONSTRAINT events_daily_p2022_01_01_pkey  (ID 6379 OID 49840)
pg_dump:   FK CONSTRAINT fk_parent_event_id_events_daily  (ID 9643 OID 49805)
pg_dump:   INDEX ATTACH events_daily_p2022_01_01_pkey  (ID 8269)

**Comment by vitabaks** [comment]
> warning: could not resolve dependency loop among these items

this warning applies to data not to script logic

Here's what I found: https://github.com/citusdata/citus/issues/866

**Comment by vitabaks** [comment]
Added automatic allocation of a PostgreSQL port from the port range https://github.com/vitabaks/pgbackrest_auto/pull/8/commits/323879debf5da74a8103119ecece71e458ab71cf
